// src/app/components/header/header.component.ts
import { Component, OnInit } from '@angular/core';
import { FlashMessagesService } from 'angular2-flash-messages';
import { AuthService } from '../../services/auth/auth.service';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css']
})
export class HeaderComponent implements OnInit {
  constructor(
    private flashMessages: FlashMessagesService,
    private auth: AuthService) {}

  ngOnInit() {
  }

  login() {
    this.auth.login('root@root.com', 'root00')
      .then(data => {
        this.flashMessages.show(`Welcome ${this.auth.user}`,
         {
           cssClass: 'alert-info',
           timeout: 3000
         });
         console.log(this.auth.user);
      });
  }

  logout() {
    this.auth.logout();
    this.flashMessages.show('You are logged out',
      {
        cssClass: 'alert-success',
        timeout: 3000
      });
  }
}

<nav class="navbar navbar-toggleable-md navbar-inverse fixed-top">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="#" [routerLink]="['/']">
    <span><i class="fa fa-leaf"></i> Lone RPG</span>
  </a>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="#" [routerLink]="['/']">Home <span class="sr-only">(current)</span></a>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <li *ngIf="!auth.user" class="nav-item">
        <a class="nav-link" href="#" (click)="login()">Login</a>
      </li>
      <li *ngIf="!auth.user" class="nav-item">
        <a class="nav-link" href="#" [routerLink]="['/register']">Register</a>
      </li>
      <li *ngIf="auth.user" class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {{ auth.user?.displayName }}
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdown01">
          <a class="dropdown-item" href="#" [routerLink]="['/profile']">Profile</a>
          <a class="dropdown-item" href="#" [routerLink]="['/settings']">Settings</a>
          <a class="dropdown-item" href="#" (click)="logout()">Logout</a>
        </div>
      </li>
    </ul>
  </div>
</nav>

// src/components/Header.vue
<template>
  <header>
    <nav class="navbar navbar-toggleable-md navbar-inverse">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <router-link class="navbar-brand" :to="{ name: 'home' }">
        <span><i class="fa fa-leaf"></i> Lone RPG</span>
      </router-link>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item" :class="{ active: $route.name === 'home' }">
            <router-link class="nav-link" :to="{ name: 'home' }">Home</router-link>
          </li>
          <li class="nav-item" :class="{ active: $route.name === 'login' }">
            <router-link  class="nav-link" :to="{ name: 'login' }">Login</router-link>
          </li>
          <li class="nav-item" :class="{ active: $route.name === 'register' }">
            <router-link  class="nav-link" :to="{ name: 'register' }">Register</router-link>
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item dropdown">
            <router-link class="nav-link dropdown-toggle" :to="$route.path" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              User
            </router-link>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
              <router-link class="dropdown-item" to="#">Profile</router-link>
              <router-link class="dropdown-item" to="#">Settings</router-link>
              <router-link class="dropdown-item" to="#">Logout</router-link>
            </div>
          </li>
        </ul>
      </div>
    </nav>
  </header>
</template>

<script lang="ts">
  import Vue from "vue";
  import Component from "vue-class-component";

  @Component({})
  export default class Header extends Vue {
    public msg: string = "Header message";
  }
</script>

<style scoped>
  .navbar {
    background-color: maroon;
  }

  .dropdown-menu a:hover {
    background-color: maroon;
    color: white;
  }
</style>
